spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Autoriser CORS pour toutes les routes
            allowedOrigins: "http://localhost:4200" # Frontend Angular
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#      routes:
#        - id: Userr-Service
#          uri: lb://USERR-SERVICE
#          predicates:
#            - Path=/auth/**
